
package es.jaranda.datafactory.model;

import es.jaranda.datafactory.api.model.Range;
import es.jaranda.datafactory.api.operator.RangeOperator;
import static org.junit.Assert.*;
import org.junit.Test;

/**
 * Test range iterator
 * 
 * @author Jorge
 */
public class RangeTest {
    
    private static final Integer[] NUMBERS = {15, 17, 19, 21, 23, 25};
    
    private final Range<Integer> cut = 
            new Range<Integer>(15, 25, new RangeOperator<Integer>() {
                
            @Override
            public Integer next(Integer current) {
                return current + 2;
            }
        }
    );
    
    /**
     * Compare all values generated by range with a static numbers
     */
    @Test
    public void iteratorTest() {
        int i = 0;
        for (Integer current : cut) {
            assertEquals(NUMBERS[i], current);
            i++;
        }
    }
}
